### ISSUE TITLE
Add support for network connector (read Blockchain without wallet)

### ISSUE THREAD

**Issue by esteblock** [paltalabs/soroban-react#12]

**Comment by esteblock** [comment]
How to replicate this:
Follow the instructions in https://github.com/esteblock/multichain-dapp/issues
You will see that if you don't connet your wallet, the frontend is unable to see any Blockchain.
We should be able to tell the frontend what is a default Soroban RPC

**Comment by benjaminsalon** [comment]
> How to replicate this: Follow the instructions in https://github.com/esteblock/multichain-dapp/issues You will see that if you don't connet your wallet, the frontend is unable to see any Blockchain. We should be able to tell the frontend what is a default Soroban RPC

I don't see any issues with the link you sent

**Comment by benjaminsalon** [comment]
But I understand it, when starting the multichain dapp before connecting the wallet we cannot read the title of the contract, is that what is about @esteblock ?

**Comment by esteblock** [comment]
> > How to replicate this: Follow the instructions in https://github.com/esteblock/multichain-dapp/issues You will see that if you don't connet your wallet, the frontend is unable to see any Blockchain. We should be able to tell the frontend what is a default Soroban RPC
> 
> I don't see any issues with the link you sent

I ment just [https://github.com/esteblock/multichain-dapp](https://github.com/esteblock/multichain-dapp/issues) XD

**Comment by esteblock** [comment]
> But I understand it, when starting the multichain dapp before connecting the wallet we cannot read the title of the contract, is that what is about @esteblock ?

Yes. The problem is that now we cannot read the blockchain if the user does not connects the Wallet (which provides netoworkDetails and provides the sorobanRpcUrl)

We need to set a new connector called "network" that the frontend dev will define a SorobanRpcUrl
It will be read-only

**Comment by chopan123** [comment]
How's this going?

**Comment by esteblock** [comment]
Hello @benjaminsalon This was solved in https://github.com/paltalabs/soroban-react/pull/64 and https://github.com/paltalabs/soroban-react/pull/63

However, there are still a lot of things to clean.
There is no need to have NetworkDetails, WalletChain, ChainName, ChainMetadata...
Will open a new issue for that: https://github.com/paltalabs/soroban-react/issues/70
