### ISSUE TITLE
[D2.4] Add support for xbull

### ISSUE THREAD

**Issue by esteblock** [paltalabs/soroban-react#36]
Waiting for https://github.com/Creit-Tech/xBull-Wallet-Connect/issues/2 in order to make the process faster

**Comment by esteblock** [comment]
Also please check 
https://discord.com/channels/897514728459468821/1082054027317096478/1189577366368944179
https://github.com/Creit-Tech/Stellar-Wallets-Kit

**Comment by benjaminsalon** [comment]
> I think there are new versions since my last message in June XD Can you please do an experiment using https://github.com/Creit-Tech/xBull-Wallet-Connect/ ?

Yes it is the same issue. The bridge need the window to be defined

**Comment by benjaminsalon** [comment]
> Also please check https://discord.com/channels/897514728459468821/1082054027317096478/1189577366368944179 https://github.com/Creit-Tech/Stellar-Wallets-Kit

This would probably remove the need to have our connectors on soroban-react as we would just need the kit which can handle all wallets. The kit would be the only connector, which could be nice @esteblock

**Comment by benjaminsalon** [comment]
New obstacle encountered:
xBull doesn't expose a getNetworkDetails method like freighter but the library is built on top of this method
