### ISSUE TITLE
Use user's wallet address (and/or some blank one) in `fetchContractValue`

### ISSUE THREAD

**Issue by paulbellamy** [paltalabs/soroban-react#4]
Some contract values might depend on the caller, so we should not use the hardcoded testing address. We should either take the address from the user's wallet (if available), or some sort of anonymous placeholder if it isn't.

https://github.com/esteblock/soroban-react/blob/b99fdc23e023a4174aca609affd3da352e255bd5/packages/contracts/src/useContractValue.tsx#L7-L9

https://github.com/esteblock/soroban-react/blob/b99fdc23e023a4174aca609affd3da352e255bd5/packages/contracts/src/useContractValue.tsx#L95

**Comment by esteblock** [comment]
Yes!  Will work on this tomorrow

**Comment by esteblock** [comment]
I see you opened PR, will check it out now

**Comment by esteblock** [comment]
https://github.com/paltalabs/soroban-react/blob/4a2dd567b9d41f1a04f8f27997da51ca9d166337/packages/contracts/src/useContractValue.tsx#L45C61-L45C75

**Comment by esteblock** [comment]
https://github.com/paltalabs/soroban-react/blob/main/packages/contracts/src/defaultAddress.tsx
