### ISSUE TITLE
If the wallet does not provide a SorobanRpcUrl we should handle the error

### ISSUE THREAD

**Issue by esteblock** [paltalabs/soroban-react#51]
Currently, if the user does not have correcly set his network, and does not provide a SorobanRpcUrl, the user cannot sign the tx and does not know what is happening.
We should handle this error and pass the error to the frontend so the frontend shows a message to the user

**Comment by benjaminsalon** [comment]
This PR #52 is throwing an error if the soroban rpc url is not set. The error still needs to be handled in the frontend for better ui

**Comment by esteblock** [comment]
@benjaminsalon please make that the boilerplate handles this error and then help us in soroswap to handle it the same way: https://github.com/soroswap/frontend/issues/131

**Comment by benjaminsalon** [comment]
Ok @esteblock !
